### ISSUE TITLE
Fix DockerHub build 

### ISSUE THREAD

**Issue by Fire-Swan** [DonairSauce/shrekbot#43]
Current version is 8 months old

**Comment by TaylorTWBrown** [comment]
Where are the details man? You gotta describe the problem if you want it fixed.

Anyways, our current builds only publish to GHCR, and there's interest in also pushing builds to DockerHub, which we've mostly abandoned. I will look into updating ou GH Actions to also push to our docker org.

**Comment by TaylorTWBrown** [comment]
Resolved with #44
